name: matematika
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  cloud_firestore: 4.13.3
  firebase_core: 2.24.2
  chewie: 1.7.4
  video_player: 2.8.1
  flutter_html: ^3.0.0-beta.2
  syncfusion_flutter_charts: 24.1.44+1
  firebase_auth: 4.16.0
  flutter_widget_from_html: ^0.9.1
  # flutter_widget_from_html: ^0.15.0
  email_validator: 2.1.17
  whiteboard: 0.0.2
  hive: 2.2.3
  # whiteboard_sdk_flutter: 0.5.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/videos/
  uses-material-design: true

