// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZZpL6k5Reg-wkYjaprYgpRoL5BtM_oU',
    appId: '1:235209867581:web:52636ae489386d10558554',
    messagingSenderId: '235209867581',
    projectId: 'matematika-d1820',
    authDomain: 'matematika-d1820.firebaseapp.com',
    storageBucket: 'matematika-d1820.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd_k-7fGI7-Ir2Z7UmaSZAI00YxvtNqHg',
    appId: '1:235209867581:android:1821cd623a31a0e1558554',
    messagingSenderId: '235209867581',
    projectId: 'matematika-d1820',
    storageBucket: 'matematika-d1820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHM5muEKnBYdw2HXSTTbLxc0mkvr5xuTA',
    appId: '1:235209867581:ios:09666e88305d7e34558554',
    messagingSenderId: '235209867581',
    projectId: 'matematika-d1820',
    storageBucket: 'matematika-d1820.appspot.com',
    iosBundleId: 'com.example.matematika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHM5muEKnBYdw2HXSTTbLxc0mkvr5xuTA',
    appId: '1:235209867581:ios:9863d4983499c115558554',
    messagingSenderId: '235209867581',
    projectId: 'matematika-d1820',
    storageBucket: 'matematika-d1820.appspot.com',
    iosBundleId: 'com.example.matematika.RunnerTests',
  );
}
